### ISSUE TITLE
🐛 Available Work Types page throws an error

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#202]
# Summary

ref [convo](https://assaydepot.slack.com/archives/C0313NK5NMA/p1713378651628729)

In prep for the mobius demo we've discovered the https://mobius-staging.staging.hykuup.com/admin/work_types/edit page crashes.

The error traces back to a view file (/app/samvera/app/views/admin/work_types/edit.html.erb)that does NOT exist in the repo, and therefore shouldn't be on the server (but it is) :thinking_face:

We tried to manually delete it off the server which appeared to nearly take down the site entirely - we weren't able to login (authenticity token error) which seems totally unrelated. Redeploying resolved this but now we're back in the state where this ghost file persists.

# Acceptance Criteria

- [x] Visiting the work types edit page should not result in a crash

# Screenshots or Video

# Testing Instructions

# Notes

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/3395206a-bd59-4751-ac5d-98ce7eec33ed)

**Comment by ShanaLMoore** [comment]
Kiah rebuilt base: 

- https://github.com/samvera/hyku/actions/runs/8729422098

**Comment by bkiahstroud** [comment]
Rebuilding the base Hyku image was the right call. The issue was, the HykuUP Knapsack image was cached in Rancher, so the updated image built on top of the new base didn't actually deploy. This is because the Docker image tag was the same. 

We deployed a new image with a different sha that was created after merging a PR. This resolved this issue.
